# Generated by Django 3.0.2 on 2020-01-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200106_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='amz_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
