# Generated by Django 3.0.2 on 2020-02-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_amz_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinesZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=300)),
                ('desc', models.TextField(blank=True, max_length=3000, null=True)),
                ('price', models.FloatField(default=1)),
                ('amz_link', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=400)),
                ('desc', models.TextField(blank=True, max_length=3000, null=True)),
                ('price', models.FloatField(default=1)),
                ('amz_link', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GigZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=400)),
                ('desc', models.TextField(blank=True, max_length=3000, null=True)),
                ('price', models.FloatField(default=1)),
                ('amz_link', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
