# Generated by Django 2.2.8 on 2020-03-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_busineszone_gamezone_gigzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='busineszone',
            name='img_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='gamezone',
            name='img_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='gigzone',
            name='img_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='img_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
