# Generated by Django 2.2.8 on 2020-03-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200308_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busineszone',
            name='img_url',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='gamezone',
            name='img_url',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='gigzone',
            name='img_url',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='img_url',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
