# Generated by Django 2.2.8 on 2020-03-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200308_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='accessories',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='desktop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='laptop',
            field=models.BooleanField(default=False),
        ),
    ]
